export const ADD_FILTER = 'ACTIONS/ADD_FILTER';
export const DELETE_FILTER = 'ACTIONS/DELETE_FILTER';
export const DO_SEARCH = 'ACTIONS/DO_SEARCH';
export const ADD_SHOPPING = 'ACTIONS/ADD_TO_SHOPPING_LIST';
export const SET_INCLUDE = 'ACTIONS/SET_INCLUDE';
export const LOADING = 'ACTIONS/LOADING';
export const CLEAR_FILTER = 'ACTIONS/CLEAR_FILTER';